print("=====================")
print("Nama : Zulfadli Daniswara")
print("NIM : 064002300025")
print("=====================")
from Bangun_Datar import Persegi, PersegiPanjang, Lingkaran, Segitiga, JajarGenjang
persegi = Persegi(6)
persegipanjang = PersegiPanjang(5,7)
lingkaran = Lingkaran(4)
segitiga = Segitiga (5,8)
jajargenjang = JajarGenjang (5,4)
print("Luas Persegi adalah:", persegi.luas())
print("Luas Persegi panjang adalah:", persegipanjang.luas())
print("Luas lingkaran adalah:", lingkaran.luas())
print("Luas Segitiga dalah:", segitiga.luas())
print("Luas Jajar Genjang adalah:", jajargenjang.luas())